# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatherApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # add pods for desired Firebase products
  "https://firebase.google.com/docs/ios/setup#available-pods"

  # Pods for weatherApp

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  target 'weatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'weatherApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for weatherApp-tvOS

  target 'weatherApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
